export enum FishGameEventName {
    GAME_PLAYER_ENTER = "GAME_PLAYER_ENTER",
    GAME_PLAYER_LEAVE = "GAME_PLAYER_LEAVE",
    GAME_CANNON_FIREONCE = "GAME_CANNON_FIREONCE",
    GAME_CANNON_CHANGE = "GAME_CANNON_CHANGE",
    GAME_COST_CHANGE = "GAME_COST_CHANGE",
    GAME_PLAYER_SETCOIN = "GAME_PLAYER_SETCOIN",
    GAME_AUTOFIRE_FLAG = "GAME_AUTOFIRE_FLAG",
    GAME_AIM_FLAG = "GAME_AIM_FLAG",
    GAME_CREATE_AIMEDVIEW = "GAME_CREATE_AIMEDVIEW",
    GAME_CLEAR_AIMEDVIEW = "GAME_CLEAR_AIMEDVIEW",
    GAME_GUAJIVIE_VISIBLEW = "GAME_GUAJIVIE_VISIBLEW",
    GAME_SET_AUTO_LOCK_BTN_VIEW = "GAME_SET_AUTO_LOCK_BTN_VIEW",
    GAME_SHOW_FISHDIECOINNUM = "GAME_SHOW_FISHDIECOINNUM",
    GAME_SHOW_FISHDIEADDCOIN = "GAME_SHOW_FISHDIEADDCOIN",
    GAME_SHOW_FIRE_EFFECT = "GAME_SHOW_FIRE_EFFECT",                // 局部炸弹死亡后旋转火焰特效
    GAME_SHOW_SIMILARLIGHT = "GAME_SHOW_SIMILARLIGHT",              // 闪电鱼死亡后释放的闪电
    GAME_SHOW_LIGHT_EFFECT = "GAME_SHOW_LIGHT_EFFECT",              // 覆盖在鱼身上的闪电效果
    GAME_SHOW_BAOFU = "GAME_SHOW_BAOFU",
    GAME_SHOW_JIANGLI = "GAME_SHOW_JIANGLI",
    GAME_SHOW_JUMP_COIN = "GAME_SHOW_JUMP_COIN",                    // 显示跳动金币
    GAME_SHOW_BOSS_DIEEFFECT = "GAME_SHOW_BOSS_DIEEFFECT",          // 大鱼死亡效果
    GAME_LOAD_COMPLETE = "GAME_LOAD_COMPLETE",                      // 加载完成
    GAME_LOAD_PROGRESS = "GAME_LOAD_PROGRESS",                      // 加载中
    GAME_BOSS_COMING = "GAME_BOSS_COMING",                          // boss来袭
}