
// Code generated by xlsx2proto.
// DO NOT EDIT!

import { ConfHolder } from "./ConfLoader";

export class DB_FortuneGod_WeightCondition implements ConfHolder {
    public datas:server.DB_FortuneGod_WeightConditionArray | null = null;
    public pool:Map<number,server.DB_FortuneGod_WeightCondition> = new Map<number,server.DB_FortuneGod_WeightCondition>();
    private static instacne:DB_FortuneGod_WeightCondition | null = null;

    public static getInstance():DB_FortuneGod_WeightCondition{
        if (this.instacne == null){
            this.instacne = new DB_FortuneGod_WeightCondition();
        }
        return this.instacne;
    }

    //反序列化
    decode(buff: Uint8Array): Error|null {
        this.datas = server.DB_FortuneGod_WeightConditionArray.decode(buff);
        this.arrangeData();
        return null;
    }

    //
    public clear():void{
        this.datas =null;
        this.pool.clear();
        DB_FortuneGod_WeightCondition.instacne = null;
    }

    //将数组转换成为字典
    private arrangeData(){
        if (this.datas != null){
            for (let k of this.datas.Arr.keys()){
                let id = this.datas.Arr[k].Id;
                this.pool.set(id!,this.datas.Arr[k] as server.DB_FortuneGod_WeightCondition)
            }
        }
    }
}
