
// Code generated by xlsx2proto.
// DO NOT EDIT!

import { ConfHolder } from "./ConfLoader";

export class DB_Game_Pet implements ConfHolder {
    public datas:server.DB_Game_PetArray | null = null;
    public pool:Map<number,server.DB_Game_Pet> = new Map<number,server.DB_Game_Pet>();
    private static instacne:DB_Game_Pet | null = null;

    public static getInstance():DB_Game_Pet{
        if (this.instacne == null){
            this.instacne = new DB_Game_Pet();
        }
        return this.instacne;
    }

    //反序列化
    decode(buff: Uint8Array): Error|null {
        this.datas = server.DB_Game_PetArray.decode(buff);
        this.arrangeData();
        return null;
    }

    //
    public clear():void{
        this.datas =null;
        this.pool.clear();
        DB_Game_Pet.instacne = null;
    }

    //将数组转换成为字典
    private arrangeData(){
        if (this.datas != null){
            for (let k of this.datas.Arr.keys()){
                let id = this.datas.Arr[k].Id;
                this.pool.set(id!,this.datas.Arr[k] as server.DB_Game_Pet)
            }
        }
    }
}
